services:
  - type: web
    name: habit-tracker-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
